services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  echo:
    image: mendhak/http-https-echo:31
    ports:
      - "8080:8080"

  ip-allocator-webserver:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - echo
    environment:
      - REDIS_URL=redis://redis:6379/
    volumes:
      - ./config.toml:/etc/ip-allocator/config.toml:ro
    command: ["ip-allocator-webserver", "--config", "/etc/ip-allocator/config.toml"]

volumes:
  redis_data: